### ISSUE TITLE
Azurite Emulator Support

### ISSUE THREAD

**Issue by webteckie** [sebagomez/azurestorageexplorer#136]
How feasible is it to add support for this to play nice with the local emulator (e.g. azurite) where you do not have to signin to azure? When I run a version of Azure Storage Explorer installed in my labtop I can access a local emulator no problem without login to azure. Wondering if that is or would be possible with the dockerized version.

**Comment by sebagomez** [comment]
Hello @webteckie, that's a good question. I'm don't know how the local emulator works but I'm guessing it exposes the same API. So that would make it possible. 
I'll take a look to figure out what's needed.

**Comment by MazeChaZer** [comment]
I guess the main blocker for this is supporting [IP-style URLs](https://github.com/Azure/Azurite?tab=readme-ov-file#endpoint--connection-url), custom port numbers, and HTTP instead of HTTPS.

On top of that, convenience features would be nice, like a “Connect to local emulator” button that connects to the localhost with the [default storage account of the emulator](https://github.com/Azure/Azurite?tab=readme-ov-file#default-storage-account) on the [default ports](https://github.com/Azure/Azurite?tab=readme-ov-file#run-azurite-v3-docker-image) 10000/10001/10002, or a Docker environment variable that configures this storage explorer to directly connect to the emulator.

This web-based storage explorer would be an awesome addition to a local development setup that relies on the Azurite emulator.
