### ISSUE TITLE
Custom blob endpoint URL

### ISSUE THREAD

**Issue by StenGruener** [sebagomez/azurestorageexplorer#74]
Hi,

thank you for the work! Could it be possible to be able to set alternative blob endpoints?

I wanted to use your tool with local azurite: https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string

So adding a possibility to enter a custom connection string, e.g., instead of username with an empty password would be great.

Thanks
-Sten

**Comment by sebagomez** [comment]
Hey @StenGruener , that was actually in my mind and the code behind already supports it (at least some of it)
I have not been able to test it myself because I don't have an alternative endpoint myself.
Will take a look at the link you shared, and the possibility of adding a custom connection string. cheers

**Comment by sebagomez** [comment]
hey @StenGruener I did some major changes and the option for custom endpoints is now available. Let me know if you get the chance to tryit.

Cheers
